select name 
from ships 
inner join Classes on ships.class = Classes.class


where (numGuns = 8 and bore = 15  and displacement = 32000 and type = 'bb')
OR (numGuns = 8 and bore = 15  and displacement = 32000 and launched = 1915 )
OR (numGuns = 8 and bore = 15  and displacement = 32000 and ships.class='Kongo')
OR (numGuns = 8 and bore = 15  and displacement = 32000 and country='USA')
OR (numGuns = 8 and bore = 15  and type = 'bb' and launched = 1915 )
OR (numGuns = 8 and bore = 15  and type = 'bb' and ships.class='Kongo')
OR (numGuns = 8 and bore = 15  and type = 'bb' and country='USA')
OR (numGuns = 8 and bore = 15  and launched = 1915  and ships.class='Kongo')
OR (numGuns = 8 and bore = 15  and launched = 1915  and country='USA')
OR (numGuns = 8 and bore = 15  and ships.class='Kongo' and country='USA')
OR (numGuns = 8 and displacement = 32000 and type = 'bb' and launched = 1915 )
OR (numGuns = 8 and displacement = 32000 and type = 'bb' and ships.class='Kongo')
OR (numGuns = 8 and displacement = 32000 and type = 'bb' and country='USA')
OR (numGuns = 8 and displacement = 32000 and launched = 1915  and ships.class='Kongo')
OR (numGuns = 8 and displacement = 32000 and launched = 1915  and country='USA')
OR (numGuns = 8 and displacement = 32000 and ships.class='Kongo' and country='USA')
OR (numGuns = 8 and type = 'bb' and launched = 1915  and ships.class='Kongo')
OR (numGuns = 8 and type = 'bb' and launched = 1915  and country='USA')
OR (numGuns = 8 and type = 'bb' and ships.class='Kongo' and country='USA')
OR (numGuns = 8 and launched = 1915  and ships.class='Kongo' and country='USA')
OR (bore = 15  and displacement = 32000 and type = 'bb' and launched = 1915 )
OR (bore = 15  and displacement = 32000 and type = 'bb' and ships.class='Kongo')
OR (bore = 15  and displacement = 32000 and type = 'bb' and country='USA')
OR (bore = 15  and displacement = 32000 and launched = 1915  and ships.class='Kongo')
OR (bore = 15  and displacement = 32000 and launched = 1915  and country='USA')
OR (bore = 15  and displacement = 32000 and ships.class='Kongo' and country='USA')
OR (bore = 15  and type = 'bb' and launched = 1915  and ships.class='Kongo')
OR (bore = 15  and type = 'bb' and launched = 1915  and country='USA')
OR (bore = 15  and type = 'bb' and ships.class='Kongo' and country='USA')
OR (bore = 15  and launched = 1915  and ships.class='Kongo' and country='USA')
OR (displacement = 32000 and type = 'bb' and launched = 1915  and ships.class='Kongo')
OR (displacement = 32000 and type = 'bb' and launched = 1915  and country='USA')
OR (displacement = 32000 and type = 'bb' and ships.class='Kongo' and country='USA')
OR (displacement = 32000 and launched = 1915  and ships.class='Kongo' and country='USA')
OR (type = 'bb' and launched = 1915  and ships.class='Kongo' and country='USA')
